// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoS-ByTpigGCO0hy7ZgDrCyVpIgw_gDJ4',
    appId: '1:623843752290:android:bab5f3000114a7bf64543b',
    messagingSenderId: '623843752290',
    projectId: 'database-test-database',
    databaseURL: 'https://database-test-database.firebaseio.com',
    storageBucket: 'database-test-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFukiyMLrhT_syPeP7QeEPKjovZSz8bKk',
    appId: '1:623843752290:ios:e0a26bc1117e0d8d64543b',
    messagingSenderId: '623843752290',
    projectId: 'database-test-database',
    databaseURL: 'https://database-test-database.firebaseio.com',
    storageBucket: 'database-test-database.firebasestorage.app',
    iosClientId: '623843752290-drqdelkkhc8mts7bp1798e0orntm2r7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoFlutterApp',
  );
}
